// <auto-generated />
namespace NUOVO.Migrations.MigrationsB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migrazione2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrazione2));
        
        string IMigrationMetadata.Id
        {
            get { return "202110060949499_Migrazione2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
